Update TargetRubyVersion to 2.5
Starting from 1.12 rubocop doesn't support ruby 2.4:

```
Error: RuboCop found unsupported Ruby version 2.4 in `TargetRubyVersion` parameter (in .rubocop.yml). 2.4-compatible analysis was dropped after version 1.12.
```